Vagrant.configure(2) do |config|
  config.vm.box = 'centos-7.1'
  config.vm.box_url = 'http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.1_chef-provisionerless.box'
  config.vm.network :private_network, ip: '33.33.33.10'
  config.vm.synced_folder '..', '/dind'
  config.vm.provision 'shell',inline: '/bin/bash /dind/centos/scripts/vagrant-host-setup'
end
